---
title: "Simulation design"
author: "Mathias Dah Fienon"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
require(fastICA)
require(KernelICA)
require(JADE)
require(ICtest)
# require(progress)
# require(foreach)
# require(doParallel)
```

# Simulation process

## Rotation matrix function

```{r}
rotation_matrix <- function(angle0 = pi*c(0.1, 0.25, 0.4), q = 1){
  
  angle <- angle0*q
  
  rot1 <- matrix(data = c(1, 0, 0,
                          0, cos(angle[1]), -sin(angle[1]),
                          0, sin(angle[1]), cos(angle[1])), 
                 byrow = TRUE, nrow = 3, ncol = 3)
  
  rot2 <- matrix(data = c(cos(angle[2]), 0, -sin(angle[2]),
                          0, 1, 0,
                          sin(angle[2]), 0, cos(angle[2])), 
               byrow = TRUE, nrow = 3, ncol = 3)
  
  rot3 <- matrix(data = c(cos(angle[3]), -sin(angle[3]), 0,
                          sin(angle[3]), cos(angle[2]), 0,
                        0, 0, 1), 
             byrow = TRUE, nrow = 3, ncol = 3)
  
  return(rot1 %*% rot2 %*% rot3)
}

```

##  Generation zt

```{r}
z_vector <- function(deg_f = 5, long = 1100){
  
  z1 <- rt(long, deg_f)[101:long]
  z2 <- rt(long, deg_f)[101:long]
  z3 <- rt(long, deg_f)[101:long]
  
  return(as.matrix(rbind(z1/sd(z1), z2/sd(z2),z3/sd(z3))) )
}

```

##  Generation residuals

```{r}
residuals <- function(angle0 = pi*c(0.1, 0.25, 0.4), q = 1, 
                      deg_f = 5, size = 1100){
  
  r1 <-  rotation_matrix(angle0, q) %*% z_vector(deg_f, size)
  
  r2 <- as.data.frame(t(r1))
  
  return(list(r1, r2))
}
```



## Result for amari_error for fastICA

```{r}
generator_ica <- function(angle0 = pi*c(0.1, 0.25, 0.4),q = 1,
                          deg_f = 5, size = 1100, 
                          func = "logcosh"){
  # this function will return the amari_error computed between 
  # the mixing true matrix A and the estimated unmixing matrix W
  
  mixing_matrix <-  rotation_matrix(angle0, q = 1)
  
  # get the residuals
  generated_residuals <-  residuals(angle0=angle0, q=q, 
                                   deg_f=deg_f, size=size)
  
  original  <-  generated_residuals[[1]]
  
  ica_result <- fastICA::fastICA(t(original), n.comp = 3,
                                 alg.typ = "parallel", 
                                 fun = func, 
                                 alpha = 1,
                                 method = "C")
  
  return(JADE::amari.error(mixing_matrix, ica_result$W))
  
}
```




## Result for amari_error for kernelICA

```{r}
generator_kernel_ica <- function(angle0 = pi*c(0.1, 0.25,0.4),
                                 q = 1,
                                 deg_f = 5, size = 1100, 
                                 variante = "kgv"){
  # this function will return the amari_error computed between 
  # the mixing true matrix A and the estimated unmixing matrix W
  
  mixing_matrix <-  rotation_matrix(angle0, q = 1)
  
  # get the residuals
  generated_residuals <-  residuals(angle0=angle0, q=q, 
                                   deg_f=deg_f, size=size)
  
  original  <-  generated_residuals[[1]]
  
  kernel_ica_result <- KernelICA::kernel_ica(t(original), 
                                      variant = variante,
                                      kernel = "gauss")
  
  return(JADE::amari.error(mixing_matrix, kernel_ica_result$W))
}
```


## Global simulation

```{r}
global_result <- function(q = c(1, 1.01, 1.025, 1.05), sim_size = 2){
  
  
  # this function is the core of the simulation.
  #  it run the functions 500 times and returns a dataframe of the result
  
  global_list <- c()
  the_col_names <- c()
  
  for(angle_q in q){
    
    for(df in c(5, 10,15)){
      for ( n_size in c(1100, 2100, 4100)) {
        
        ica_exp_obtained_list <- c()
        ica_logcosh_obtained_list <- c()
        kernel_ica_kgv_obtained_list = c()
        kernel_ica_kcca_obtained_list = c()
        
        for(sim in 1:sim_size){
          
          ica_exp_obtained_list <- append(ica_exp_obtained_list, generator_ica(q = angle_q, deg_f = df, size = n_size, func = "exp"))
          ica_logcosh_obtained_list <-  append(ica_logcosh_obtained_list, generator_ica(q = angle_q, deg_f = df, size = n_size, func = "logcosh"))
          kernel_ica_kgv_obtained_list <-  append(kernel_ica_kgv_obtained_list, generator_kernel_ica(q = angle_q, deg_f = df, size = n_size, variante = "kgv"))
         kernel_ica_kcca_obtained_list <-  append(kernel_ica_kcca_obtained_list, generator_kernel_ica(q = angle_q, deg_f = df, size = n_size, variante = "kcca"))
                                                       
        }
        global_list <- cbind(global_list, ica_exp_obtained_list,
                             ica_logcosh_obtained_list,
                             kernel_ica_kgv_obtained_list,
                             kernel_ica_kcca_obtained_list)
        for(meth in c("ica_exp", "ica_logcosh", "kernel_ica_kgv", "kernel_ica_kcca")){
          the_col_names <- append(the_col_names, paste(angle_q,
                                                     df,
                                                     n_size,
                                                     meth,
                                                     sep = ", "))
        }
        
      }
    }
    
  }
  
  
  result = as.data.frame(global_list, col)
  colnames(result) <- the_col_names
  rownames(result) <- 1:sim_size
  
  
  return(result)
  
}

```

```{r}
# glo3prime <- global_result(sim_size = 3)
```


## simulation results


```{r}
clockwise_rotation_result = global_result(sim_size = 500)
```

```{r}
write.csv(clockwise_rotation_result, "clockwise_rotation_result_R.csv")
```


```{r}
anti_clockwise_rotation_result = global_result(q = c(1., 0.99009901, 0.97560976, 0.95238095), sim_size = 500)
```

```{r}
write.csv(anti_clockwise_rotation_result, "anti_clockwise_rotation_result_R.csv")
```





